apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Github-pages-deploy-from-github
  title: Backstage Driven Internal Developer Platform
  description: Automates website deployment using Docker containers or GitHub Pages hosting.
spec:
  owner: user:guest
  type: service

  
  parameters:
    - title: GitHub Repository URL
      required: 
        - Github_URL
        #- Dockerfile
        #- Port
      properties:
        Github_URL:
          title: Enter you Github URL
          type: string
          description: Enter the github URL where your code exists
          ui:autofocus: true

    - title: Select where you want to deploy your code
      required:
        - stack
      properties:
        stack:
          title: Select from below list
          type: string
          enum:
            - Docker
            - Github pages
            - Baremetal
            - Kubernetes
  
    - title: Enter below details
      dependencies:
        stack:
          oneOf:
            - properties:
                stack:
                  const: Docker
                extraFields:          # 👈 wrap everything else inside a schema key
                  title: Enter the details
                  type: object
                  properties:
                    Dockerfile:
                      title: Enter the Path of Dockerfile
                      type: string
                      description: Enter the Dockerfile path (e.g. build/Dockerfile or enter Dockerfile if it is in root) 
                      default: "Dockerfile" 
                    Port:
                      title: Enter the Port number
                      type: integer
                      minimum: 1
                      maximum: 65535
                      description: Enter the Port number of your application (e.g. 80/3000/5000)
  
            - properties:
                stack:
                  const: Github pages
                extraFields:
                  type: object
                  properties:          
                      
                    GithubToken:
                      title: Enter the Github Token
                      type: string
                      description: Enter the token
                       
            - properties:
                stack:
                  const: Baremetal
                extraFields:
                  type: object
                  properties:
                    PlaybookPath:
                      title: Enter the Path of PlaybookPath
                      type: string
                      description: Enter the PlaybookPath
                      default: "playbook.yml" 
                    HostsPath:
                      title: Enter the Path of Hosts file
                      type: string
                      description: Enter the Hosts file
                      default: "hosts" 
  
            - properties:
                stack:
                  const: Kubernetes
                extraFields:
                  title: Kubernetes Deployment Details
                  type: object
                  properties:
                    DeploymentFile:
                      title: Deployment Manifest Path
                      type: string
                      description: Path to your deployment YAML file (relative to repo)
                      default: "deployment.yaml"
                    ServiceFile:
                      title: Service Manifest Path
                      type: string
                      description: Path to your service YAML file (relative to repo)
                      default: "service.yaml"
                    Namespace:
                      title: Kubernetes Namespace (optional)
                      type: string
                      description: Namespace to deploy into (leave blank for default)
                      default: "default"
          
  steps:
    - id: fetch-template
      name: Fetch template files
     # if: ${{ parameters.stack == 'Docker' }}
      action: fetch:plain
      input:
        url: ${{ parameters.Github_URL }}
        targetPath: .


    - id: build_docker
      name: Build Docker Image
      if: ${{ parameters.stack == 'Docker' }}
      action: shell:run
      input:
        cwd: ${{ steps.clone.output.path }}
        command: docker 
        args: ["build", "-f", "${{ parameters.extraFields.Dockerfile }}", "-t", "my-image:latest", "."]


    - id: cleanup
      name: Remove old container if exists
      if: ${{ parameters.stack == 'Docker' }}
      action: shell:run
      input:
        command: docker
        args: ["rm", "-f", "Cafe-container"]
                

    - id: deploy_docker
      name: Deploy Docker Container
      if: ${{ parameters.stack == 'Docker' }}
      action: shell:run
      input:
        cwd: ${{ steps.clone.output.path }}
        command: docker
        args: ["run", "--name", "Cafe-container", "-it", "-d", "-p", "89:${{ parameters.extraFields.Port }}", "my-image:latest"] 

    # - id: fetch
    #   name: Fetch GitHub Repo
    #   if: ${{ parameters.stack == 'Github pages' }}
    #   action: fetch:plain
    #   input:
    #     url: ${{ parameters.Github_URL }}
    #     #targetPath: ./site  # fetch code into ./site folder
    #     targetPath: .
   

    - id: build
      name: Prepare Static Site
      if: ${{ parameters.stack == 'Github pages' }}
      action: shell:run
      input:
        command: bash
        args:
          - -c
          - |
            set -e
            echo "🌐 Static site detected"
            echo "📍 Working directory: $(pwd)"
            echo "📂 Files present (excluding hidden):"
            find . -maxdepth 2 -not -path '*/.*'
    
            echo "📦 Creating ./dist folder"
            mkdir -p ./dist
    
            # Copy visible files from root if any
            if [ "$(ls -A | grep -v '^\.' | wc -l)" -gt 0 ]; then
              echo "📋 Copying files from root to ./dist..."
              rsync -av --exclude='.*' ./ ./dist/
            fi
    
            # Copy all non-hidden subfolders into dist
            SUBFOLDERS=$(find . -mindepth 1 -maxdepth 1 -type d -not -name '.*')
            for F in $SUBFOLDERS; do
              echo "📂 Copying contents of $F to ./dist..."
              rsync -av --exclude='.*' "$F"/ ./dist/
            done
    
            echo "✅ All static files copied to ./dist successfully!"
        #cwd: ./site
        cwd: .
        

    - id: publish
      name: Deploy Static Site to GitHub Pages
      if: ${{ parameters.stack == 'Github pages' }}
      action: shell:run
      input:
        command: bash
        args:
          - -c
          - |
            set -e
            #cd ./site/dist
            cd ./dist

            # Take the user input GitHub URL
            USER_URL="${{ parameters.Github_URL }}"
            
            # Remove trailing slash if present
            USER_URL="${USER_URL%/}"
            
            # Add token for authentication
            AUTH_URL="https://x-access-token:${{ parameters.extraFields.GithubToken }}@${USER_URL#https://}"

            git init
            git config user.email "backstage@automation.local"
            git config user.name "Backstage Bot"
            git remote add origin "$AUTH_URL"
            git checkout -b gh-pages || git checkout gh-pages
            git add .
            git commit -m "Deploy from Backstage Template"
            git push --force origin gh-pages


    # - id: fetch-kube
    #   name: Fetch Kubernetes Manifests
    #   if: ${{ parameters.stack == 'Kubernetes' }}
    #   action: fetch:plain
    #   input:
    #     url: ${{ parameters.Github_URL }}
    #     targetPath: ./kube

   
    - id: start-minikube
      name: Start Minikube Cluster
      if: ${{ parameters.stack == 'Kubernetes' }}
      action: shell:run
      input:
        command: minikube
        args: ["start", "--driver=docker"]
        
    - id: apply-kube
      name: Deploy to Kubernetes via Minikube
      if: ${{ parameters.stack == 'Kubernetes' }}
      action: shell:run
      input:
        #cwd: ./kube
        cwd: .
        command: bash
        args:
          - -c
          - |
            set -e
            echo "Applying manifests to Minikube cluster..."

            NAMESPACE="${{ parameters.extraFields.Namespace }}"
            DEPLOY="${{ parameters.extraFields.DeploymentFile }}"
            SERVICE="${{ parameters.extraFields.ServiceFile }}"

            kubectl apply -f "$DEPLOY" -n "$NAMESPACE"
            kubectl apply -f "$SERVICE" -n "$NAMESPACE"
            

  output:
    links:
      - title: "View on GitHub Pages"
        #if: "${{ parameters.deploy_method == 'github pages' }}"
        if: ${{ parameters.stack == 'Github pages' }}
        url: "https://${{ parameters.Github_URL | replace('https://github.com/', '') | replace('.git', '') | replace('/', '.github.io/') }}/"
        #url: ${{ steps.github-pages.output.pageUrl }}
        icon: "website"

      - title: "Open Website"
        if: ${{ parameters.stack == 'Docker' }}
        url: "http://localhost:89"
        icon: "website"
